### ISSUE TITLE
processor usage spike, program slows to a crawl - MacOS 

### ISSUE THREAD

**Issue by hugeblank** [MCJack123/craftos2#158]
**Describe the bug**
I'm in the process of debugging a program before release. When running the program, what is supposed to be a one second sleep becomes longer and longer until after around 10 'sleep' seconds the application becomes unresponsive and hangs. Additionally looking at the activity monitor the CPU % readout displays '200%.' This could very well be an issue with my program but I fail to see how the issue could happen with the code that I have. Terminating does not work but rebooting does.

**To Reproduce**
1. Take both of [these files](https://gist.github.com/hugeblank/845b6f9e06d586877d0493bb10d0a6a0) and run them
2. Observe it counting up from 1 to 5. At around 2-3 it begins to go slower than 1 second intervals. Additionally observe the processor spike.
3. Observe that processor usage goes down to reasonable levels once the program waits for a click at 5.
4. Click anywhere, it'll slow back down, and then completely halt at around 9.

**Expected behavior**
Program counts to 10 and well beyond without chewing computer resources.

**Screenshots**
Demonstration of processor spinning up to an ungodly amount. Note that in this clip it doesn't even count to 5 before grinding to a halt, unlike all of my previous runs. There was another minute of me sitting and waiting that got clipped out of this.
https://user-images.githubusercontent.com/16393543/102715822-b9809b00-428c-11eb-97fd-462aafb7b67d.mov

**Environment (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 2.4.5
 - Compiled from source? [No]

**Comment by MCJack123** [comment]
I noticed this in testing a few days ago, and I found that queueing a large number of events would cause CraftOS-PC to not check for key inputs, making it impossible to quit. The main culprit was by queueing two events per one event pulled, ex. having two `os.startTimer` calls in one `parallel` loop. Now by using `sleep` this shouldn't happen since it waits for the proper `timer` event before continuing, but it may still be a factor.

I've already fixed the input checking issue on the v2.5 branch. I haven't looked at your code too much yet, but the changes made may help, if not resolve this issue. Try running the latest build on the v2.5 branch (for Windows, [the latest nightly](https://www.craftos-pc.cc/nightly/)) and see if that helps at all. (I updated the DLL's for Windows recently. If you get errors about missing libraries, I can send you the latest library package.)

**Comment by hugeblank** [comment]
I only have my laptop with me for the next few weeks, I'll try compiling 2.5 from source and come back to you with results.

**Comment by hugeblank** [comment]
Ran into this beauty when compiling the app:
```hugeblank@MacBook-Pro craftos2 % make macapp
 [CXX]   obj/Computer.o
error: unable to open output file 'obj/Computer.o': 'No such file or directory'
1 error generated.
make: *** [obj/Computer.o] Error 1```

**Comment by MCJack123** [comment]
It should be making the `obj` directory automatically, but try doing `mkdir obj`.

**Comment by hugeblank** [comment]
oh wow I should have figured that out lol, thanks

but now we have this:
```
src/platform/macapp.mm:239:25: error: use of undeclared identifier 'queueTask'
                        queueTask([win, path, res, pathstr](void*)->void*{
                        ^
1 error generated.
```

**Comment by MCJack123** [comment]
1. I'd recommend running `make` and not `make macapp`, since `macapp` requires a few more resources, and is designed for building release binaries.
2. I haven't tested building on Mac for v2.5 yet, so it looks like there's something broken in the Mac app platform source. I'll fix this, but you can build the normal one (`make`) for now.

**Comment by hugeblank** [comment]
https://user-images.githubusercontent.com/16393543/102742081-e6729380-4308-11eb-9cd6-0d637b83ef0e.mov

Issue persists

**Comment by MCJack123** [comment]
Alright, I found the issue: basically, every time you pull an event it resets the timeout timer (that controls the "Too long without yielding" error) by removing it, and adding a new one after the event is pulled before returning to Lua. However, when events are being queued and pulled rapidly like your code does, it causes thousands of timers to be added and removed. This ended up overloading the timer thread, and timers would take much longer to be fired because the timer thread was busy processing the additions and removals.

I'm working on a fix right now, and I expect it to be ready within an hour.

**Comment by hugeblank** [comment]
Just to be clear, there isn't anything I could do on my end with my code to make it run with the emulator right now right? my code is alright right?

**Comment by MCJack123** [comment]
Not at the moment, as far as I can tell. You could try to stop it from repeatedly pulling events while waiting, if possible, but I'm not sure how viable this is with the current code.
